/*
turns
    try {
        statements1
    } catch (e) {
        statements2
    } finally {
        statements3
    }
=>
    try {
        console.log("Entered try statement");
        statements1
        throw "Throwing error on purpose to trigger catch block"
    } catch (e) {
        console.log("Entered catch clause");
        statements2
    } finally {
        console.log("Entered finally clause");
        statements3
    }
 */

module.exports = (args) => {
    args.block.body.unshift({
        "type": "ExpressionStatement",
        "expression": {
            "type": "CallExpression",
            "callee": {
                "type": "Identifier",
                "name": "logMultiexec"
            },
            "arguments": [
                {
                    "type": "Literal",
                    "value": `Entered try statement`,
                },
                {
                    "type": "Literal",
                    "value": 2,
                }
            ]
        }
    })
    args.block.body.push({
        "type": "ExpressionStatement",
        "expression": {
            "type": "CallExpression",
            "callee": {
                "type": "Identifier",
                "name": "logMultiexec"
            },
            "arguments": [
                {
                    "type": "Literal",
                    "value": ``,
                },
                {
                    "type": "Literal",
                    "value": 0,
                }
            ]
        }
    })
    args.block.body.push({
        "type": "ThrowStatement",
        "argument": {
            "type": "Literal",
                "value": "Throwing error on purpose to trigger catch block",
        }
    })
    args.handler.body.body.unshift({
        "type": "ExpressionStatement",
        "expression": {
            "type": "CallExpression",
            "callee": {
                "type": "Identifier",
                "name": "logMultiexec"
            },
            "arguments": [
                {
                    "type": "Literal",
                    "value": `Entered catch clause`,
                },
                {
                    "type": "Literal",
                    "value": 2,
                }
            ]
        }
    })
    args.handler.body.body.push({
        "type": "ExpressionStatement",
        "expression": {
            "type": "CallExpression",
            "callee": {
                "type": "Identifier",
                "name": "logMultiexec"
            },
            "arguments": [
                {
                    "type": "Literal",
                    "value": `Exited catch clause`,
                },
                {
                    "type": "Literal",
                    "value": 0,
                }
            ]
        }
    })
    args.finalizer ? args.finalizer.body.unshift({
                "type": "ExpressionStatement",
                "expression": {
                    "type": "CallExpression",
                    "callee": {
                        "type": "Identifier",
                        "name": "logMultiexec"
                    },
                    "arguments": [
                        {
                            "type": "Literal",
                            "value": `Entered finally clause`,
                        },
                        {
                            "type": "Literal",
                            "value": 2,
                        }
                    ]
                }
    }) : "";
    args.finalizer ? args.finalizer.body.push({
        "type": "ExpressionStatement",
        "expression": {
            "type": "CallExpression",
            "callee": {
                "type": "Identifier",
                "name": "logMultiexec"
            },
            "arguments": [
                {
                    "type": "Literal",
                    "value": `Exited finally clause`,
                },
                {
                    "type": "Literal",
                    "value": 0,
                }
            ]
        }
    }) : "";
    return {
        autogenerated: true,
        type: args.type,
        block: args.block,
        handler: args.handler,
        finalizer: args.finalizer,
    }
};
