const window = {
    //https://developer.mozilla.org/en-US/docs/Web/API/Window
    properties: [
        //[propertyName, readOnly]
        ["clientInformation", true],
        ["closed", true],
        // ["console", true],
        ["crypto", true],
        ["devicePixelRatio", true],
        // ["document", true],
        ["fullScreen", true],
        ["history", true],
        ["innerHeight", true],
        ["innerWidth", true],
        // ["length", true],
        ["location", false],
        ["localStorage", true],
        ["name", false],
        ["navigator", true],
        ["opener", false],
        ["outerHeight", true],
        ["outerWidth", true],
        ["pageXOffset", true],
        ["pageYOffset", true],
        ["parent", true],
        ["screen", true],
        ["screenX", true],
        ["screenY", true],
        ["screenLeft", true],
        ["screenTop", true],
        ["scrollbars", true],
        // ["scrollMaxX", true],
        // ["scrollMaxY", true],
        ["scrollX", true],
        ["scrollY", true],
        ["sessionStorage", false],
        ["speechSynthesis", true],
        ["status", false],
        ["toolbar", true],
        ["top", true],

        ["origin", true],
    ],
    methods: [
        ["alert"],
        ["blur"],
        ["clearImmediate"],
        ["close"],
        ["confirm"],
        ["dump"],
        ["focus"],
        ["getSelection"],
        ["moveBy"],
        ["moveTo"],
        ["open"],
        ["postMessage"],
        ["prompt"],
        ["resizeBy"],
        ["resizeTo"],
        ["scroll"],
        ["scrollBy"],
        ["scrollTo"],
        ["setImmediate"],
        ["stop"],
        ["atob"], //TODO: probably want to log the argument too
        ["btoa"],
        ["clearInterval"],
        ["clearTimeout"],
        ["fetch"],
        ["setInterval"],
        ["setTimeout"],
        ["reportError"],
        ["reportError"],
    ]
}

module.exports = {
    window
}